In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
bank_marketing = fetch_ucirepo(id=222) 
  
# data (as pandas dataframes) 
X = bank_marketing.data.features 
Y = bank_marketing.data.targets 
  
# metadata 
print(bank_marketing.metadata) 
  
# variable information 
print(bank_marketing.variables) 



{'uci_id': 222, 'name': 'Bank Marketing', 'repository_url': 'https://archive.ics.uci.edu/dataset/222/bank+marketing', 'data_url': 'https://archive.ics.uci.edu/static/public/222/data.csv', 'abstract': 'The data is related with direct marketing campaigns (phone calls) of a Portuguese banking institution. The classification goal is to predict if the client will subscribe a term deposit (variable y).', 'area': 'Business', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 45211, 'num_features': 16, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Age', 'Occupation', 'Marital Status', 'Education Level'], 'target_col': ['y'], 'index_col': None, 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Fri Aug 18 2023', 'dataset_doi': '10.24432/C5K306', 'creators': ['S. Moro', 'P. Rita', 'P. Cortez'], 'intro_paper': {'title': 'A data-driven approach to predict the success of bank telemarketing'

In [4]:
import pandas as pd
import numpy as np
import time 

In [5]:
df = pd.DataFrame(X)
df.head()

df_model = df.iloc[:,0:4]
df_model.dropna(inplace=True)
df_model['marital'] = df_model['marital'].str.replace("divorced", "single")

In [6]:
df_model_1 = df_model.reset_index(drop=True)
df_model_1

age           job  marital  education
0       58    management  married   tertiary
1       44    technician   single  secondary
2       33  entrepreneur  married  secondary
3       35    management  married   tertiary
4       28    management   single   tertiary
...    ...           ...      ...        ...
43188   51    technician  married   tertiary
43189   71       retired   single    primary
43190   72       retired  married  secondary
43191   57   blue-collar  married  secondary
43192   37  entrepreneur  married  secondary

[43193 rows x 4 columns]

In [7]:
bagımsız_age = df_model_1.iloc[:,[0]]
bagımsız_age

age
0       58
1       44
2       33
3       35
4       28
...    ...
43188   51
43189   71
43190   72
43191   57
43192   37

[43193 rows x 1 columns]

In [8]:
bagımsız_age

age
0       58
1       44
2       33
3       35
4       28
...    ...
43188   51
43189   71
43190   72
43191   57
43192   37

[43193 rows x 1 columns]

In [9]:
bagımlı = df_model_1.iloc[:,2:3]
bagımlı

marital
0      married
1       single
2      married
3      married
4       single
...        ...
43188  married
43189   single
43190  married
43191  married
43192  married

[43193 rows x 1 columns]

In [10]:
bagımsız_job = df_model_1.iloc[:,[1]]
bagımsız_job.head()

job
0    management
1    technician
2  entrepreneur
3    management
4    management

In [11]:
from sklearn import preprocessing
bagımsız_job = bagımsız_job.values

ohe = preprocessing.OneHotEncoder() 
bagımsız_job = ohe.fit_transform(bagımsız_job).toarray()
print(bagımsız_job)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [12]:
bagımsız_education = df_model_1.iloc[:,[3]]
bagımsız_education


education
0       tertiary
1      secondary
2      secondary
3       tertiary
4       tertiary
...          ...
43188   tertiary
43189    primary
43190  secondary
43191  secondary
43192  secondary

[43193 rows x 1 columns]

In [13]:
from sklearn import preprocessing
bagımsız_education = bagımsız_education.values

ohe = preprocessing.OneHotEncoder() 
bagımsız_education = ohe.fit_transform(bagımsız_education).toarray()
print(bagımsız_education)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [14]:
bagımsız_job_sonuc= pd.DataFrame(data=bagımsız_job,columns=["admin","blue-collar","entrepreneur","management","retired","self-employed","services","housemaid","student","technician","unemployed"])
bagımsız_job_sonuc.head()

admin  blue-collar  entrepreneur  management  retired  self-employed  \
0    0.0          0.0           0.0         0.0      1.0            0.0   
1    0.0          0.0           0.0         0.0      0.0            0.0   
2    0.0          0.0           1.0         0.0      0.0            0.0   
3    0.0          0.0           0.0         0.0      1.0            0.0   
4    0.0          0.0           0.0         0.0      1.0            0.0   

   services  housemaid  student  technician  unemployed  
0       0.0        0.0      0.0         0.0         0.0  
1       0.0        0.0      0.0         1.0         0.0  
2       0.0        0.0      0.0         0.0         0.0  
3       0.0        0.0      0.0         0.0         0.0  
4       0.0        0.0      0.0         0.0         0.0

In [15]:
bagımsız_education_sonuc= pd.DataFrame(data=bagımsız_education,columns=["tertiary","secondary","primary"])
bagımsız_education_sonuc.head()

tertiary  secondary  primary
0       0.0        0.0      1.0
1       0.0        1.0      0.0
2       0.0        1.0      0.0
3       0.0        0.0      1.0
4       0.0        0.0      1.0

In [16]:
# burada kaldım yukarıdaki kodlar okey # b => bağımsızların dataframei, df_model_last ise genel model dataframei


# b => bağımsızların dataframei, df_model_last ise genel model dataframei

a = pd.concat([bagımsız_education_sonuc,bagımsız_job_sonuc],axis=1)
b = pd.concat([a,bagımsız_age],axis=1)
df_model_last = pd.concat([b,bagımlı],axis=1)
df_model_last

tertiary  secondary  primary  admin  blue-collar  entrepreneur  \
0           0.0        0.0      1.0    0.0          0.0           0.0   
1           0.0        1.0      0.0    0.0          0.0           0.0   
2           0.0        1.0      0.0    0.0          0.0           1.0   
3           0.0        0.0      1.0    0.0          0.0           0.0   
4           0.0        0.0      1.0    0.0          0.0           0.0   
...         ...        ...      ...    ...          ...           ...   
43188       0.0        0.0      1.0    0.0          0.0           0.0   
43189       1.0        0.0      0.0    0.0          0.0           0.0   
43190       0.0        1.0      0.0    0.0          0.0           0.0   
43191       0.0        1.0      0.0    0.0          1.0           0.0   
43192       0.0        1.0      0.0    0.0          0.0           1.0   

       management  retired  self-employed  services  housemaid  student  \
0             0.0      1.0            0.0       0.0        0.0      0.0   
1             0.0      0.0            0.0       0.0        0.0      0.0   
2             0.0      0.0            0.0       0.0        0.0      0.0   
3             0.0      1.0            0.0       0.0        0.0      0.0   
4             0.0      1.0            0.0       0.0        0.0      0.0   
...           ...      ...            ...       ...        ...      ...   
43188         0.0      0.0            0.0       0.0        0.0      0.0   
43189         0.0      0.0            1.0       0.0        0.0      0.0   
43190         0.0      0.0            1.0       0.0        0.0      0.0   
43191         0.0      0.0            0.0       0.0        0.0      0.0   
43192         0.0      0.0            0.0       0.0        0.0      0.0   

       technician  unemployed  age  marital  
0             0.0         0.0   58  married  
1             1.0         0.0   44   single  
2             0.0         0.0   33  married  
3             0.0         0.0   35  married  
4             0.0         0.0   28   single  
...           ...         ...  ...      ...  
43188         1.0         0.0   51  married  
43189         0.0         0.0   71   single  
43190         0.0         0.0   72  married  
43191         0.0         0.0   57  married  
43192         0.0         0.0   37  married  

[43193 rows x 16 columns]

In [17]:
b_values = b.values

In [18]:
bagımlı_values = bagımlı.values

# Part 2:
Build a classifier based on KNN (K=4 for testing) using Manhattan distance.  
You are expected to code the KNN classifier by yourself. 
Report performance using an appropriate k-fold cross validation using confusion matrices on the given dataset.  
Report the run time performance of your above tests. 

In [19]:
#verilerin egitim ve test icin bolunmesi
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(b_values,bagımlı_values,test_size=0.33, random_state=0)


In [20]:
x_train

array([[ 0.,  1.,  0., ...,  0.,  1., 42.],
       [ 0.,  1.,  0., ...,  0.,  0., 33.],
       [ 0.,  1.,  0., ...,  0.,  0., 29.],
       ...,
       [ 1.,  0.,  0., ...,  0.,  0., 49.],
       [ 0.,  0.,  1., ...,  0.,  0., 40.],
       [ 1.,  0.,  0., ...,  0.,  0., 42.]])

In [21]:
x_test

array([[ 0.,  1.,  0., ...,  0.,  0., 34.],
       [ 0.,  1.,  0., ...,  0.,  0., 47.],
       [ 0.,  0.,  1., ...,  0.,  0., 30.],
       ...,
       [ 0.,  1.,  0., ...,  0.,  0., 60.],
       [ 1.,  0.,  0., ...,  0.,  0., 49.],
       [ 0.,  0.,  1., ...,  0.,  0., 50.]])

In [22]:
#öznitelik ölçekleme
#veriler standartlaştırıldı

from sklearn.preprocessing import StandardScaler

sc = StandardScaler() 

X_train = sc.fit_transform(x_train)  #büyük X e dönüştürdük
X_test = sc.transform(x_test)


In [23]:
X_train.shape

(28939, 15)

In [24]:
X_test.shape

(14254, 15)

In [25]:
y_test.shape

(14254, 1)

In [26]:
y_train.shape

(28939, 1)

In [27]:
#KNN !
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=4, metric='manhattan') #parametre vericemi komşu defoultu 5   
#neighbors sayısını azalttık ve matrixde sonuç inanılmaz değişti.

knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
#Buradan sonra confision matrixi kullanacam.

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [28]:
#confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred) 
print(cm)


[[7316 1263]
 [3851 1824]]


# Part 3: 
* Build a classifier based on linear SVM. 
* You may use an available implementation of SVM in Python. 
* Report performance using an appropriate k-fold cross validation using ROC curves and confusion matrices. 
* Report the run time performance of your above tests. 

In [29]:
from sklearn.svm import SVC 
svc = SVC(kernel = 'poly') #regresyondaki lineer polinomial vs yazdığımız parametrenin adı kernel idi.

#linear ile doğrsular bir ayrım arayacak 
svc.fit(X_train,y_train)
y_pred = svc.predict(X_test)



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [30]:
cm = confusion_matrix(y_test,y_pred)
print('SVC_poly')
print(cm)


SVC_poly
[[6797 1782]
 [2944 2731]]


# Part 4:
Build a classifier based on polynomial SVM.  
You may use an available implementation of SVM in Python. 
Report performance using an appropriate k-fold cross validation using ROC curves and confusion matrices. Find the best threshold for the SVM output as described in the note by Fawcett.  
Report the run time performance of your above tests. 

In [31]:
svc_linear = SVC(kernel = 'linear') #regresyondaki lineer polinomial vs yazdığımız parametrenin adı kernel idi.

#linear ile doğrsular bir ayrım arayacak 
svc_linear.fit(X_train,y_train)
y_pred2 = svc_linear.predict(X_test)


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [32]:
y_pred2

array(['married', 'married', 'single', ..., 'married', 'married',
       'married'], dtype=object)

In [33]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test,y_pred2)
print('SVC_linear')
print(cm2)

SVC_linear
[[6754 1825]
 [2884 2791]]


# Part 1:
Build a classifier based on KNN (K=4 for testing) using Euclidean distance.   
You are expected to code the KNN classifier by yourself. 
Report performance using an appropriate k-fold cross validation using confusion matrices on the given dataset. 
Report the run time performance of your above tests. 

In [34]:
import numpy as np
from collections import Counter

from numpy.linalg import norm



class KNearestNeighbors:
    


    def euclidean(a, b):
        
        """Compute and return the euclidean distance between a and b."""
        return norm(a-b)

    def __init__(self, k=3, distance_metric=euclidean):
        """Initialize k value and distance metric used for model."""
        self.k = k
        self.distance = distance_metric
        self.data = None

    def train(self, X, y):
        """Zip labels and input data together for classification."""
        # raise value error if inputs are wrong length or different types
        if len(X) != len(y) or type(X) != type(y):
            raise ValueError("X and y are incompatible.")
        # convert ndarrays to lists
        if type(X) == np.ndarray:
            X, y = X.tolist(), y.tolist()
        # set data attribute containing instances and labels
        self.data = [X[i]+[y[i]] for i in range(len(X))]

    def predict(self, a):
        """Predict class based on k-nearest neighbors."""
        neighbors = []
        # create mapping from distance to instance
        distances = {self.distance(x[:-1], a): x for x in self.data}
        # collect classes of k instances with shortest distance
        for key in sorted(distances.keys())[:self.k]:
            neighbors.append(distances[key][-1])
        # return most common vote
        return max(set(neighbors), key=neighbors.count)
    
            


In [37]:
#KNN !
from sklearn.neighbors import KNeighborsClassifier

knn2 = KNearestNeighbors(k=4) #parametre vericemi komşu defoultu 5   
#neighbors sayısını azalttık ve matrixde sonuç inanılmaz değişti.

knn2.train(X_train,y_train)
y_pred2 = knn.predict(X_test)




In [38]:
#confusion matrix

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred2) 
print(cm)


[[7316 1263]
 [3851 1824]]
